(use gl.processing)

(define draw (draw-once$ (^ ()
                       (translate 280 25)
                       (dotimes (i 5)
                         (let1 c (quotient 255 (+ i 1))
                           (fill c c c)
                           (rect 0 0 50 50)
                           (fill 40 40 40)
                           (text (number->string c) 15 65))
                         (translate -50 0))
                       (fill 0 0 0)
                       (rect 0 0 50 50)
                       (fill 40 40 40)
                       (text "0" 15 65))
                    :save "grayscale.png"))
(define main (setup$ (^ ()
                        (window 360 100 "Grayscale Color" 100 100)
                        (font-mode! 'bitmap)
                        (load-font "Utopia" 14))
                     :draw draw))
(main '())