(use gl.processing)

(define (draw-grid xn yn margin)
  (let ((w (* margin (+ 1 xn)))
        (h (* margin (+ 1 yn))))
    (fill 0)
    (dotimes (i yn)
      (let1 y (* (+ i 1) margin)
        (text (number->string (- yn i 1)) (+ 5 w) y)
        (line 0 y w y)))
    (dotimes (i xn)
      (let1 x (* (+ i 1) margin)
        (text (number->string i) (- x 5) (+ 20 h))
        (line x 0 x h)))))

(define draw (draw-once$ (^ ()
                            (with-matrix
                             (translate 25 25)
                             (draw-grid 5 6 20)

                             (stroke-weight 2)
                             (line 40 120 100 20)
                             (ellipse 100 20 5 5)
                             (ellipse 40 120 5 5))
                       )
                         :bg (cut background 255)
                         :save ".png"))
(define main (setup$ (^ () 
                        (window 200 200 "coord" 100 100)
                        (font-mode! 'bitmap)
                        (load-font "Utopia" 12)
                        )
                     :draw draw))

(main '())